---
- name: Web app issue

  hosts: all
  sources:
   - ansible.eda.kafka:
       host: rhel01-nostromo.demoredhat.com
       port: 9092
       topic: network

  rules:
   - name: http config issue
   #  condition: event.body.syslog.facility == "3" and event.body.journald.unit is match("httpd.service") and event.body.message is match("Failed to start The Apache HTTP Server.")
     condition: event.body.message is match("Failed to start The Apache HTTP Server.")
     action:
       run_job_template:
        organization: "Default"
        name: "Restore Web Application"